# Generated by Django 3.1.7 on 2021-03-04 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_workplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingworkplace',
            name='booking_date',
            field=models.DateField(default=datetime.date(2021, 3, 4), verbose_name='Дата бронирования'),
        ),
        migrations.AddField(
            model_name='bookingworkplace',
            name='cabinet',
            field=models.IntegerField(default=0, verbose_name='Номер кабинета'),
        ),
        migrations.AddField(
            model_name='bookingworkplace',
            name='user',
            field=models.CharField(default='', max_length=250, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='bookingworkplace',
            name='workplace',
            field=models.IntegerField(default=0, verbose_name='Номер рабочего места'),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='booking_date',
            field=models.DateField(default=datetime.date(2021, 3, 4), verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingworkplace',
            name='end_time',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='bookingworkplace',
            name='start_time',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], verbose_name='Начало работы'),
        ),
    ]
